version: "3.9"

services:

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"  # Включить API Traefik (не использовать в продакшн)
      - "--providers.docker=true"  # Включить провайдер Docker
      - "--entrypoints.http.address=:80"  # Настроить точку входа для HTTP
      - "--entrypoints.https.address=:443"  # Настроить точку входа для HTTPS
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"  # Настройка HTTP-01 challenge
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.myresolver.acme.email=abakarov_gm1@mail.ru"  # Замените на ваш email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"  # Хранилище сертификатов
    ports:
      - "8080:8080"  # Порт для панели управления Traefik
      - "80:80"  # Порт для HTTP трафика
      - "443:443"  # Порт для HTTPS трафика
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Подключение Docker сокета
      - "letsencrypt:/letsencrypt"  # Хранилище для сертификатов Let's Encrypt
    networks:
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev"

  api:
    image: gadjimurad112233/apteka-risunki:api-1.0.0
    volumes:
      - uploads:/app/storage/app/public
    networks:
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.abakarov`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.docker.network=dev"
      - "traefik.http.routers.api.entryPoints=http"
      - "traefik.http.routers.api-secure.entryPoints=https"
      - "traefik.http.routers.api-secure.rule=Host(`api.abakarov.store`)"
      - "traefik.http.routers.api-secure.tls.certresolver=myresolver"

  panel:
    image: gadjimurad112233/apteka-risunki:panel-1.0.0
    networks:
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`panel.abakarov`)"
      - "traefik.http.services.panel.loadbalancer.server.port=80"
      - "traefik.docker.network=dev"
      - "traefik.http.routers.panel.entryPoints=http"
      - "traefik.http.routers.panel-secure.entryPoints=https"
      - "traefik.http.routers.panel-secure.rule=Host(`panel.abakarov.store`)"
      - "traefik.http.routers.panel-secure.tls.certresolver=myresolver"

  api-php-fpm:
    image: gadjimurad112233/apteka-risunki:php-fpm-1.0.0
    volumes:
      - uploads:/app/storage/app/public
    environment: # Переменные окружения для Laravel
      APP_NAME: Аптека рисунки 120/80
      APP_URL: https://api.abakarov.store
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: secret
    networks:
      - dev

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - dbVolume:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - "5432:5432"

networks:
  dev:
    name: dev

volumes:
  uploads:
  dbVolume:
    driver: local
  letsencrypt:  # Хранилище для сертификатов Let's Encrypt
